# Generated by Django 4.2.3 on 2024-09-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile',
            new_name='Company',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, default=11, on_delete=django.db.models.deletion.CASCADE, to='store.company'),
            preserve_default=False,
        ),
    ]
